SENHASEGURA_URL: "https://10.10.10.100/"
SENHASEGURA_CLIENT_ID: "4a979feb588e7b02660c24179f17e351"
SENHASEGURA_CLIENT_SECRET: "eab0f16cab8d9fed781eac8335fdebf0c8cd38966644f6eadba098837387b916"
#SENHASEGURA_MAPPING_FILE: "<Secrets variable name mapping file with path>"
#SENHASEGURA_SECRETS_FILE: "<File name with path to inject Secret>"
SENHASEGURA_DISABLE_RUNB: 0
